### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by anajetli** [moemoe89/Simple-realtime-message-SocketIO-NodeJS-CI#1]
getting message :

internal server error

**Comment by alejandrotoga02** [comment]
@anajetli  Are you using Ubuntu ???

**Comment by anajetli** [comment]
No sir I'm on wamp.

**Comment by alejandrotoga02** [comment]
I think the problem is the old version of mysql bd,
in the  read_status column.
ALTER TABLE `realtime_message`.`message` 
CHANGE COLUMN `read_status` `read_status` TINYINT(1) NOT NULL DEFAULT 0 ;

**Comment by alejandrotoga02** [comment]
@anajetli  try this ^

**Comment by anajetli** [comment]
wOW! now its working.... Thank you so much AlexToga02.
I am new to node and it will help me alot in building apps on node.

**Comment by moemoe89** [comment]
@AlexToga02 thank you for your help. closed now.
