### ISSUE TITLE
error in sockit.io.js

### ISSUE THREAD

**Issue by knizer** [moemoe89/Simple-realtime-message-SocketIO-NodeJS-CI#3]
socket.io.js:2919 GET http://localhost:3000/socket.io/?EIO=3&transport=polling&t=1469192570460-0 net::ERR_CONNECTION_REFUSED

in console

**Comment by allennic** [comment]
![image](https://cloud.githubusercontent.com/assets/7100774/19473247/5f9ce19c-955d-11e6-8333-88d3f16b3c4c.png)

what should i do?
can i delete the `read_status` col?

**Comment by vandolphreyes** [comment]
@knizer, run the websocket using node. In your console, run "node server.js"

**Comment by vandolphreyes** [comment]
@allennic, it was just your mysql issue. Set your SQL mode to blank.
1. Go to localhost/phpmyadmin
2. Click VARIABLES tab
3. Select SQL_MODE and edit to blank
